apiVersion: v1
kind: ConfigMap
metadata:
  name: cavern-service-roguelike
  # name: {{ include "cavern-service-roguelike.name" . }}
data:
  defaults.json: |
    {
      "cavepath": "/usr/src/app/config/caves/caves.json"
    }
