apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "entrance-roguelike.name" . }}
data:
  defaults.json: |
    {
    "cave_id": 0,
    "gateways": "http://entrance:3000/caves",
    "width":15,
    "height":10,
    "depth":3,
    "generator" : "FileGenerator",
    "maps":"./src/server/config/maps/entrance",
    "cavepath": "/usr/src/app/config/caves/caves.json"
    }
