apiVersion: v1
kind: Service
metadata:
  name: {{ include "cave-roguelike.name" . }}
  labels:
    {{- include "cave-roguelike.labels" . | nindent 4 }}
spec:
  type: {{ .Values.deploy.serviceType }}
  selector:
    {{- include "cave-roguelike.selectorLabels" . | nindent 4 }}
  ports:
    {{- tpl (toYaml .Values.deploy.ports) . | nindent 4 }}